trigger:
- main

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: '1cf87dd9-eed1-4b6f-b67b-ddc82a24c1ae'
  imageRepository: 'qhomebaseapigateway'
  containerRegistry: 'qhome.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/QhomeBase/api-gateway/Dockerfile'
  tag: '$(Build.BuildId)'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build and push stage
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
    # Docker
    - task: Docker@2
      inputs:
        containerRegistry: 'qhome'
        repository: 'qhome'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        buildContext: '${System.DefaultWorkingDirectory}'
        tags: |
          $(Build.BuildId)
          latest
    # Build and push an image to Azure Container Registry
    # https://docs.microsoft.com/azure/devops/pipelines/languages/docker
