name: 'qhome-base'
services:
  # Infrastructure Services
  qhome-rabbitmq:
    image: rabbitmq:4.0.4-management
    container_name: qhome-rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 30s
      timeout: 30s
      retries: 10
    deploy:
      resources:
        limits:
          memory: 500m

  mailhog:
    image: mailhog/mailhog:v1.0.1
    container_name: qhome-mailhog
    ports:
      - "1025:1025"
      - "8025:8025"

  keycloak:
    image: quay.io/keycloak/keycloak:26.3.0
    command: [ 'start-dev', '--import-realm', '--http-port=9191' ]
    container_name: qhome-keycloak
    hostname: keycloak
    volumes:
      - ./realm-config:/opt/keycloak/data/import
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin1234
    ports:
      - "9191:9191"
    deploy:
      resources:
        limits:
          memory: 2gb

  # QHome Base Microservices
  base-service:
    build:
      context: ../../base-service
      dockerfile: Dockerfile
    container_name: base-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SWAGGER_API_GATEWAY_URL=http://api-gateway:8989/base
    ports:
      - "8081:8081"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 700m

  data-docs-service:
    build:
      context: ../../data-docs-service
      dockerfile: Dockerfile
    container_name: data-docs-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SWAGGER_API_GATEWAY_URL=http://api-gateway:8989/data-docs
    ports:
      - "8082:8082"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 700m

  services-card-service:
    build:
      context: ../../services-card-service
      dockerfile: Dockerfile
    container_name: services-card-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SWAGGER_API_GATEWAY_URL=http://api-gateway:8989/services-card
    ports:
      - "8083:8083"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 700m

  asset-maintenance-service:
    build:
      context: ../../asset-maintenance-service
      dockerfile: Dockerfile
    container_name: asset-maintenance-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SWAGGER_API_GATEWAY_URL=http://api-gateway:8989/asset-maintenance
    ports:
      - "8084:8084"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 700m

  finance-billing-service:
    build:
      context: ../../finance-billing-service
      dockerfile: Dockerfile
    container_name: finance-billing-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SWAGGER_API_GATEWAY_URL=http://api-gateway:8989/finance-billing
      - DB_URL=jdbc:postgresql://postgres:5432/qhome_base_db?currentSchema=billing,finance,public
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - SPRING_FLYWAY_URL=jdbc:postgresql://postgres:5432/qhome_base_db
      - SPRING_FLYWAY_USER=postgres
      - SPRING_FLYWAY_PASSWORD=postgres
      - RABBITMQ_HOST=qhome-rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=guest
      - RABBITMQ_PASSWORD=guest
    ports:
      - "8085:8085"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 700m

  customer-interaction-service:
    build:
      context: ../../customer-interaction-service
      dockerfile: Dockerfile
    container_name: customer-interaction-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SWAGGER_API_GATEWAY_URL=http://api-gateway:8989/customer-interaction
    ports:
      - "8086:8086"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 700m

  staff-work-service:
    build:
      context: ../../staff-work-service
      dockerfile: Dockerfile
    container_name: staff-work-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SWAGGER_API_GATEWAY_URL=http://api-gateway:8989/staff-work
    ports:
      - "8087:8087"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 700m

  iam-service:
    build:
      context: ../../iam-service
      dockerfile: Dockerfile
    container_name: iam-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SWAGGER_API_GATEWAY_URL=http://api-gateway:8989/iam
      - DB_URL=jdbc:postgresql://postgres:5432/qhome_base_db?currentSchema=iam,data,public
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - SPRING_FLYWAY_URL=jdbc:postgresql://postgres:5432/qhome_base_db
      - SPRING_FLYWAY_USER=postgres
      - SPRING_FLYWAY_PASSWORD=postgres
      - RABBITMQ_HOST=qhome-rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=guest
      - RABBITMQ_PASSWORD=guest
    ports:
      - "8088:8088"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 700m

  api-gateway:
    build:
      context: ../../api-gateway
      dockerfile: Dockerfile
    container_name: api-gateway
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - BASE_SERVICE_URL=http://base-service:8081
      - DATA_DOCS_SERVICE_URL=http://data-docs-service:8082
      - SERVICES_CARD_SERVICE_URL=http://services-card-service:8083
      - ASSET_MAINTENANCE_SERVICE_URL=http://asset-maintenance-service:8084
      - FINANCE_BILLING_SERVICE_URL=http://finance-billing-service:8085
      - CUSTOMER_INTERACTION_SERVICE_URL=http://customer-interaction-service:8086
      - STAFF_WORK_SERVICE_URL=http://staff-work-service:8087
      - IAM_SERVICE_URL=http://iam-service:8088
    ports:
      - "8989:8989"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 700m


  postgres:
    image: postgres:17
    container_name: qhome-postgres
    environment:
      - POSTGRES_DB=qhome_base_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d qhome_base_db -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 10
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: